# Generated by Django 5.2.3 on 2025-07-04 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piecemeal_app', '0006_remove_plannedmeal_date_plannedmeal_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plannedmeal',
            name='day',
            field=models.CharField(choices=[('saved', 'Saved'), ('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=10),
        ),
    ]
