# Generated by Django 5.2.3 on 2025-07-05 04:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('piecemeal_app', '0007_alter_plannedmeal_day'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlannedMeal',
            new_name='ScheduleEntry',
        ),
    ]
