# Generated by Django 5.2.3 on 2025-07-05 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piecemeal_app', '0008_rename_plannedmeal_scheduleentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduleentry',
            name='meal',
        ),
        migrations.AddField(
            model_name='scheduleentry',
            name='food_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='piecemeal_app.fooditem'),
        ),
        migrations.AddField(
            model_name='scheduleentry',
            name='quantity',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='scheduleentry',
            name='day',
            field=models.CharField(max_length=10),
        ),
    ]
