# Generated by Django 5.2.3 on 2025-07-11 04:50

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('piecemeal_app', '0009_remove_scheduleentry_meal_scheduleentry_food_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduleentry',
            name='day',
        ),
        migrations.AddField(
            model_name='scheduleentry',
            name='days',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], default='Monday', max_length=56),
            preserve_default=False,
        ),
    ]
