# Generated by Django 5.2.3 on 2025-07-12 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piecemeal_app', '0010_remove_scheduleentry_day_scheduleentry_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='quantity',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='unit',
            field=models.CharField(choices=[('tsp', 'teaspoon (tsp)'), ('tbsp', 'tablespoon (tbsp)'), ('cup', 'cup'), ('oz', 'ounce (oz)'), ('lb', 'pound (lb)'), ('g', 'gram (g)'), ('kg', 'kilogram (kg)'), ('each', 'each'), ('slice', 'slice')], default='g', max_length=10),
            preserve_default=False,
        ),
    ]
