# Generated by Django 5.2.3 on 2025-07-12 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piecemeal_app', '0011_fooditem_quantity_fooditem_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealentry',
            name='unit',
            field=models.CharField(choices=[('g', 'g'), ('oz', 'oz'), ('kg', 'kg'), ('lb', 'lb'), ('tsp', 'tsp'), ('tbsp', 'tbsp'), ('cup', 'cup'), ('servings', 'servings'), ('each', 'each')], default='g', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='unit',
            field=models.CharField(choices=[('g', 'g'), ('oz', 'oz'), ('kg', 'kg'), ('lb', 'lb'), ('tsp', 'tsp'), ('tbsp', 'tbsp'), ('cup', 'cup'), ('servings', 'servings'), ('each', 'each')], max_length=10),
        ),
    ]
