# Generated by Django 5.2.3 on 2025-07-12 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piecemeal_app', '0012_mealentry_unit_alter_fooditem_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleentry',
            name='unit',
            field=models.CharField(choices=[('g', 'g'), ('oz', 'oz'), ('kg', 'kg'), ('lb', 'lb'), ('tsp', 'tsp'), ('tbsp', 'tbsp'), ('cup', 'cup'), ('servings', 'servings'), ('each', 'each')], default='100.0', max_length=10),
            preserve_default=False,
        ),
    ]
