# Generated by Django 5.2.3 on 2025-07-19 02:59

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('piecemeal_app', '0013_scheduleentry_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='aisle',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('produce', 'Produce'), ('frozen', 'Frozen')], default='produce', max_length=14),
            preserve_default=False,
        ),
    ]
