# Generated by Django 5.2.3 on 2025-07-19 13:45

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piecemeal_app', '0014_fooditem_aisle'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='makes',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='aisle',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('produce', '🍎 Produce'), ('bakery', '🍞 Bakery'), ('frozen', '🧊 Frozen'), ('sauce', '🍶 Condiments & Sauces'), ('deli', '🍗 Deli'), ('canned', '🥫 Canned'), ('health', '💊 Vitamins & Supplements'), ('baking', '🥣 Baking & Spices'), ('pasta', '🍝 Pasta, Rice & Grains'), ('dry', '🍽 Dry & Staple Foods'), ('snacks', '🍪 Snacks'), ('beverages', '🧃 Beverages'), ('dairy', '🥛 Dairy'), ('other', 'Other')], default='other', max_length=92),
        ),
    ]
