# Generated by Django 5.2.3 on 2025-07-19 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piecemeal_app', '0015_fooditem_makes_alter_fooditem_aisle'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
