# Generated by Django 5.2.3 on 2025-07-22 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piecemeal_app', '0016_fooditem_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='common_csv_filename',
            field=models.CharField(default='', max_length=20),
        ),
    ]
