# Generated by Django 5.2.3 on 2025-07-25 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piecemeal_app', '0018_alter_fooditem_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='unit',
            field=models.CharField(choices=[('g', 'g'), ('oz', 'oz'), ('kg', 'kg'), ('lb', 'lb'), ('tsp', 'tsp'), ('tbsp', 'tbsp'), ('cup', 'cup'), ('L', 'L'), ('mL', 'mL'), ('servings', 'servings'), ('each', 'each')], max_length=10),
        ),
        migrations.AlterField(
            model_name='mealentry',
            name='unit',
            field=models.CharField(choices=[('g', 'g'), ('oz', 'oz'), ('kg', 'kg'), ('lb', 'lb'), ('tsp', 'tsp'), ('tbsp', 'tbsp'), ('cup', 'cup'), ('L', 'L'), ('mL', 'mL'), ('servings', 'servings'), ('each', 'each')], max_length=10),
        ),
        migrations.AlterField(
            model_name='scheduleentry',
            name='unit',
            field=models.CharField(choices=[('g', 'g'), ('oz', 'oz'), ('kg', 'kg'), ('lb', 'lb'), ('tsp', 'tsp'), ('tbsp', 'tbsp'), ('cup', 'cup'), ('L', 'L'), ('mL', 'mL'), ('servings', 'servings'), ('each', 'each')], max_length=10),
        ),
    ]
