# Generated by Django 5.2.3 on 2025-07-25 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piecemeal_app', '0019_alter_fooditem_unit_alter_mealentry_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='fiber',
            field=models.FloatField(default=0),
        ),
    ]
